// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ball_type::Ball;
use super::capsule_type::Capsule;
use super::convex_hull_type::ConvexHull;
use super::cuboid_type::Cuboid;
use super::heightfield_type::Heightfield;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum CollisionShape {
    None,

    Cuboid(Cuboid),

    Ball(Ball),

    Capsule(Capsule),

    Heightfield(Heightfield),

    ConvexHull(ConvexHull),
}

impl __sdk::InModule for CollisionShape {
    type Module = super::RemoteModule;
}
