// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::quat_type::Quat;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RotateObjectArgs {
    pub id: u64,
    pub rotation: Quat,
}

impl From<RotateObjectArgs> for super::Reducer {
    fn from(args: RotateObjectArgs) -> Self {
        Self::RotateObject {
            id: args.id,
            rotation: args.rotation,
        }
    }
}

impl __sdk::InModule for RotateObjectArgs {
    type Module = super::RemoteModule;
}

pub struct RotateObjectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rotate_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rotate_object {
    /// Request that the remote module invoke the reducer `rotate_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_rotate_object`] callbacks.
    fn rotate_object(&self, id: u64, rotation: Quat) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `rotate_object`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RotateObjectCallbackId`] can be passed to [`Self::remove_on_rotate_object`]
    /// to cancel the callback.
    fn on_rotate_object(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &Quat) + Send + 'static,
    ) -> RotateObjectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_rotate_object`],
    /// causing it not to run in the future.
    fn remove_on_rotate_object(&self, callback: RotateObjectCallbackId);
}

impl rotate_object for super::RemoteReducers {
    fn rotate_object(&self, id: u64, rotation: Quat) -> __sdk::Result<()> {
        self.imp
            .call_reducer("rotate_object", RotateObjectArgs { id, rotation })
    }
    fn on_rotate_object(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Quat) + Send + 'static,
    ) -> RotateObjectCallbackId {
        RotateObjectCallbackId(self.imp.on_reducer(
            "rotate_object",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RotateObject { id, rotation },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, rotation)
            }),
        ))
    }
    fn remove_on_rotate_object(&self, callback: RotateObjectCallbackId) {
        self.imp.remove_on_reducer("rotate_object", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `rotate_object`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_rotate_object {
    /// Set the call-reducer flags for the reducer `rotate_object` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn rotate_object(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_rotate_object for super::SetReducerFlags {
    fn rotate_object(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("rotate_object", flags);
    }
}
