// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::asset_kind_type::AssetKind;
use super::collision_shape_type::CollisionShape;
use super::quat_type::Quat;
use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldObject {
    pub id: u64,
    pub asset: AssetKind,
    pub translation: Vec3,
    pub rotation: Quat,
    pub scale: Vec3,
    pub collision_shape: CollisionShape,
}

impl __sdk::InModule for WorldObject {
    type Module = super::RemoteModule;
}
