// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::capsule_y_data_type::CapsuleYData;
use super::heightfield_data_type::HeightfieldData;
use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum CollisionShape {
    None,

    Box(Vec3),

    Sphere(f32),

    CapsuleY(CapsuleYData),

    Heightfield(HeightfieldData),

    ConvexHull(Vec<Vec3>),
}

impl __sdk::InModule for CollisionShape {
    type Module = super::RemoteModule;
}
