// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertAssetArgs {
    pub asset_path: String,
}

impl From<InsertAssetArgs> for super::Reducer {
    fn from(args: InsertAssetArgs) -> Self {
        Self::InsertAsset {
            asset_path: args.asset_path,
        }
    }
}

impl __sdk::InModule for InsertAssetArgs {
    type Module = super::RemoteModule;
}

pub struct InsertAssetCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_asset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_asset {
    /// Request that the remote module invoke the reducer `insert_asset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_insert_asset`] callbacks.
    fn insert_asset(&self, asset_path: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `insert_asset`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InsertAssetCallbackId`] can be passed to [`Self::remove_on_insert_asset`]
    /// to cancel the callback.
    fn on_insert_asset(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> InsertAssetCallbackId;
    /// Cancel a callback previously registered by [`Self::on_insert_asset`],
    /// causing it not to run in the future.
    fn remove_on_insert_asset(&self, callback: InsertAssetCallbackId);
}

impl insert_asset for super::RemoteReducers {
    fn insert_asset(&self, asset_path: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("insert_asset", InsertAssetArgs { asset_path })
    }
    fn on_insert_asset(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> InsertAssetCallbackId {
        InsertAssetCallbackId(self.imp.on_reducer(
            "insert_asset",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::InsertAsset { asset_path },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, asset_path)
            }),
        ))
    }
    fn remove_on_insert_asset(&self, callback: InsertAssetCallbackId) {
        self.imp.remove_on_reducer("insert_asset", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `insert_asset`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_insert_asset {
    /// Set the call-reducer flags for the reducer `insert_asset` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn insert_asset(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_insert_asset for super::SetReducerFlags {
    fn insert_asset(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("insert_asset", flags);
    }
}
