// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveObjectArgs {
    pub id: u64,
    pub translation: Vec3,
}

impl From<MoveObjectArgs> for super::Reducer {
    fn from(args: MoveObjectArgs) -> Self {
        Self::MoveObject {
            id: args.id,
            translation: args.translation,
        }
    }
}

impl __sdk::InModule for MoveObjectArgs {
    type Module = super::RemoteModule;
}

pub struct MoveObjectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_object {
    /// Request that the remote module invoke the reducer `move_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_object`] callbacks.
    fn move_object(&self, id: u64, translation: Vec3) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_object`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveObjectCallbackId`] can be passed to [`Self::remove_on_move_object`]
    /// to cancel the callback.
    fn on_move_object(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec3) + Send + 'static,
    ) -> MoveObjectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_object`],
    /// causing it not to run in the future.
    fn remove_on_move_object(&self, callback: MoveObjectCallbackId);
}

impl move_object for super::RemoteReducers {
    fn move_object(&self, id: u64, translation: Vec3) -> __sdk::Result<()> {
        self.imp
            .call_reducer("move_object", MoveObjectArgs { id, translation })
    }
    fn on_move_object(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec3) + Send + 'static,
    ) -> MoveObjectCallbackId {
        MoveObjectCallbackId(self.imp.on_reducer(
            "move_object",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MoveObject { id, translation },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, translation)
            }),
        ))
    }
    fn remove_on_move_object(&self, callback: MoveObjectCallbackId) {
        self.imp.remove_on_reducer("move_object", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_object`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_object {
    /// Set the call-reducer flags for the reducer `move_object` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_object(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_object for super::SetReducerFlags {
    fn move_object(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("move_object", flags);
    }
}
