// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::vec_3_type::Vec3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ScaleObjectArgs {
    pub id: u64,
    pub scale: Vec3,
}

impl From<ScaleObjectArgs> for super::Reducer {
    fn from(args: ScaleObjectArgs) -> Self {
        Self::ScaleObject {
            id: args.id,
            scale: args.scale,
        }
    }
}

impl __sdk::InModule for ScaleObjectArgs {
    type Module = super::RemoteModule;
}

pub struct ScaleObjectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `scale_object`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait scale_object {
    /// Request that the remote module invoke the reducer `scale_object` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_scale_object`] callbacks.
    fn scale_object(&self, id: u64, scale: Vec3) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `scale_object`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ScaleObjectCallbackId`] can be passed to [`Self::remove_on_scale_object`]
    /// to cancel the callback.
    fn on_scale_object(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec3) + Send + 'static,
    ) -> ScaleObjectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_scale_object`],
    /// causing it not to run in the future.
    fn remove_on_scale_object(&self, callback: ScaleObjectCallbackId);
}

impl scale_object for super::RemoteReducers {
    fn scale_object(&self, id: u64, scale: Vec3) -> __sdk::Result<()> {
        self.imp
            .call_reducer("scale_object", ScaleObjectArgs { id, scale })
    }
    fn on_scale_object(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec3) + Send + 'static,
    ) -> ScaleObjectCallbackId {
        ScaleObjectCallbackId(self.imp.on_reducer(
            "scale_object",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ScaleObject { id, scale },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, scale)
            }),
        ))
    }
    fn remove_on_scale_object(&self, callback: ScaleObjectCallbackId) {
        self.imp.remove_on_reducer("scale_object", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `scale_object`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_scale_object {
    /// Set the call-reducer flags for the reducer `scale_object` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn scale_object(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_scale_object for super::SetReducerFlags {
    fn scale_object(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("scale_object", flags);
    }
}
