// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::collision_shape_type::CollisionShape;
use super::quat_type::Quat;
use super::vec_3_type::Vec3;
use super::world_object_type::WorldObject;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_objects`.
///
/// Obtain a handle from the [`WorldObjectsTableAccess::world_objects`] method on [`super::RemoteTables`],
/// like `ctx.db.world_objects()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_objects().on_insert(...)`.
pub struct WorldObjectsTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldObject>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_objects`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldObjectsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldObjectsTableHandle`], which mediates access to the table `world_objects`.
    fn world_objects(&self) -> WorldObjectsTableHandle<'_>;
}

impl WorldObjectsTableAccess for super::RemoteTables {
    fn world_objects(&self) -> WorldObjectsTableHandle<'_> {
        WorldObjectsTableHandle {
            imp: self.imp.get_table::<WorldObject>("world_objects"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldObjectsInsertCallbackId(__sdk::CallbackId);
pub struct WorldObjectsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WorldObjectsTableHandle<'ctx> {
    type Row = WorldObject;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldObject> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldObjectsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldObjectsInsertCallbackId {
        WorldObjectsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldObjectsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldObjectsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldObjectsDeleteCallbackId {
        WorldObjectsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldObjectsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldObject>("world_objects");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct WorldObjectsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldObjectsTableHandle<'ctx> {
    type UpdateCallbackId = WorldObjectsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldObjectsUpdateCallbackId {
        WorldObjectsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldObjectsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<WorldObject>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldObject>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `world_objects`,
/// which allows point queries on the field of the same name
/// via the [`WorldObjectsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_objects().id().find(...)`.
pub struct WorldObjectsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldObject, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldObjectsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_objects`.
    pub fn id(&self) -> WorldObjectsIdUnique<'ctx> {
        WorldObjectsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldObjectsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<WorldObject> {
        self.imp.find(col_val)
    }
}
